[book]
authors = ["mjiee"]
language = "en"
multilingual = false
src = "src"
title = "scaffold-gin"
description="gin web应用案例"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/mjiee/scaffold-gin.git"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/mjiee/scaffold-gin/edit/master/{path}"
site-url = "/scaffold-gin/"
cname="book.mjiee.top"
input-404 = "assets/404.md"

[output.html.fold]
enable = true
level = 0
